### ISSUE TITLE
navbar onSelect stops working properly with bootstap addon

### ISSUE THREAD

**Issue by cor3000** [zkoss-demo/zk-bootstrap#3]
onSelect does only fire for 1st level navitems in bl mold, and never in default mold

  <zk>
	bs mold onSelect does not work for subnavigation items

	<navbar onSelect="alert(event);" >
		<navitem label="aaa"/>
		<navitem label="bbb"/>
		<nav label="ccc">
			<navitem label="aaa"/>
			<navitem label="bbb"/>
		</nav>
	</navbar>

	default mold onSelect does not work at all

	<navbar onSelect="alert(event);" mold="default"  >
		<navitem label="aaa"/>
		<navitem label="bbb"/>
		<nav label="ccc">
			<navitem label="aaa"/>
			<navitem label="bbb"/>
		</nav>
	</navbar>
  </zk>

**Comment by shenliow** [comment]
fixed on Aug 12, 2016

**Comment by cor3000** [comment]
using the default mold still doesn't react to onSelect
```
<navbar mold="default" onSelect='Clients.log("nav: " + event)'>
  <nav label="Customer">
   <navitem label="Support" />
   <navitem label="Pricing" />
  </nav>
  <nav label="Products">
   <navitem label="By Category" />
   <navitem label="By Price" />
   <nav label="Products">
    <navitem label="By Category" />
    <navitem label="By Price" />
   </nav>
  </nav>
  <navitem label="Contact" />
 </navbar>
```
